name: Pylint CI check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  python-code-format:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Display Python version
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run Pylint
        run: |
          pylint **/*.py --fail-under=9.0