name: Pylint CI check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  python-code-format:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install PDM
        run: pip install pdm 
     
      - name: Display Python version
        run: python --version

      - name: Install dependencies
        run: pdm install 

      - name: Run Pylint
        run: pdm run pylint **/*.py --fail-under=9.0
